AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DEX-API Trigger Response Archive Lambda Function

Parameters:
  S3BucketName:
    Type: String
    Description: S3 bucket name for storing archived trigger responses
    Default: dex-trigger-archive
  
  DBSecretName:
    Type: String
    Description: AWS Secrets Manager secret name for database credentials
    Default: dex-archive/db-credentials
  
  APISecretName:
    Type: String
    Description: AWS Secrets Manager secret name for API credentials
    Default: dex-archive/api-credentials
  
  DexApiBaseUrl:
    Type: String
    Description: Base URL for DEX API
    Default: https://api.example.com
  
  VpcSecurityGroupIds:
    Type: CommaDelimitedList
    Description: Security group IDs for Lambda VPC configuration (if needed)
    Default: ""
  
  VpcSubnetIds:
    Type: CommaDelimitedList
    Description: Subnet IDs for Lambda VPC configuration (if needed)
    Default: ""

Conditions:
  UseVpc: !Not [!Equals [!Join ['', !Ref VpcSubnetIds], '']]

Resources:
  # S3 Bucket for archived trigger responses
  TriggerArchiveBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 90
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Application
          Value: DEX-Trigger-Archive
        - Key: Environment
          Value: Production

  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DexTriggerArchiveLambdaRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - !If
          - UseVpc
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
          - !Ref AWS::NoValue
      Policies:
        - PolicyName: DexTriggerArchivePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObject
                Resource: !Sub '${TriggerArchiveBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !GetAtt TriggerArchiveBucket.Arn
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${DBSecretName}*'
                  - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${APISecretName}*'
      Tags:
        - Key: Application
          Value: DEX-Trigger-Archive

  # Lambda Function
  DexTriggerArchiveFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dex-trigger-response-archive
      Description: Archives DEX-API trigger file responses to S3
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      CodeUri: .
      MemorySize: 512
      Timeout: 900
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName
          DB_SECRET_NAME: !Ref DBSecretName
          API_SECRET_NAME: !Ref APISecretName
          DEX_API_BASE_URL: !Ref DexApiBaseUrl
          TRIGGER_DATE_OFFSET_DAYS: '0'
      VpcConfig: !If
        - UseVpc
        - SecurityGroupIds: !Ref VpcSecurityGroupIds
          SubnetIds: !Ref VpcSubnetIds
        - !Ref AWS::NoValue
      Tags:
        Application: DEX-Trigger-Archive
        Environment: Production

  # CloudWatch Log Group
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${DexTriggerArchiveFunction}'
      RetentionInDays: 30

  # CloudWatch Alarm for Lambda Errors
  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: DexTriggerArchive-Lambda-Errors
      AlarmDescription: Alert when Lambda function has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref DexTriggerArchiveFunction
      TreatMissingData: notBreaching

  # CloudWatch Alarm for Lambda Duration
  LambdaDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: DexTriggerArchive-Lambda-Duration
      AlarmDescription: Alert when Lambda function duration approaches timeout
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Maximum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 840000  # 14 minutes (warning before 15 min timeout)
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref DexTriggerArchiveFunction
      TreatMissingData: notBreaching

Outputs:
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt DexTriggerArchiveFunction.Arn
    Export:
      Name: DexTriggerArchiveFunctionArn
  
  S3BucketName:
    Description: Name of the S3 bucket for archived triggers
    Value: !Ref TriggerArchiveBucket
    Export:
      Name: DexTriggerArchiveBucketName
  
  LambdaRoleArn:
    Description: ARN of the Lambda execution role
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: DexTriggerArchiveRoleArn
